Liveness Integration with IDV
aws-samples/rekognition-identity-verification pull request #33
Opened 2023-04-24 16:09 UTC by vineetkachhawaha

*Description of changes:*
Rekognition Liveness Integration with IDV

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-26 16:49 UTC, dr-natetorious requested changes
Please include one change per pull request. This helps minimize regressions and reduces review complexity. Resubmit once you remove anything not related to Liveness Detection.

Thanks.

2023-04-26 16:49 UTC, dr-natetorious commented on infra/userportal/functions/definitions.py
> +    return 'StartLivenessSesstion'
Session

2023-04-26 16:49 UTC, dr-natetorious commented on infra/userportal/gateway/topology.py
> +    "input": "{ \\"inputRequest\\": $util.escapeJavaScript($input).replaceAll("\\'", "'") }"
Why?

2023-04-26 16:49 UTC, dr-natetorious commented on infra/userportal/gateway/topology.py
> +        resource = self.rest_api.root.add_resource(
Confirm changes to this file are ADDITIVE only

2023-04-26 16:49 UTC, dr-natetorious commented on infra/userportal/states/register_idcard.py
> +    # Index the user and complete the operation...
What changes are happening to the state machines? Also remove the code that's changing, don't comment out whole files.

2023-04-26 16:49 UTC, dr-natetorious commented on infra/userportal/topology.py
> -    self.debug_state_machines = RivUserPortalStateMachines(self,'DebugStates',
Undo

2023-04-26 16:49 UTC, dr-natetorious commented on one-click.sh
> -export API_END_POINT=`awscliv2 cloudformation describe-stacks --stack-name $RIV_STACK_NAME --query "Stacks[0].Outputs[0].OutputValue" --output text`
How does this work now?

2023-04-26 16:49 UTC, dr-natetorious commented on one-click.sh
> +CDK_REGION=S3_REGION cdk deploy -a ./app.py --require-approval never
logic for s3_region is removed above

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/README.md
> +### `npm start`
thid is command not eader

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/README.md
> +### `npm test`
these are commands not headers

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/amplify.yml
> +        - npm i
`i` for install?

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/public/manifest.json
> +  "short_name": "React App",
undo / be consistent

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/public/manifest.json
> +  "name": "Create React App Sample",
avoid calling this react sample app -- its RIV Demo

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/src/App.js
> +Auth.configure({
Does everyone need cogniti now?

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/src/App.js
> +                name: "identityverification",
spelling

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/src/Error.js
> + 'UserAlreadyExists' : 'Sorry, user already exist!. Delete user to try out this feature',
error messages are a neutral tone

2023-04-26 16:49 UTC, dr-natetorious commented on src/frontend/src/Pages/Home.js
> +
remove whitespace

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/check-userid/handler.py
> +    if userId in faces:
you probly mean to `throw UserAlreadyExistsError("message here")`

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/check-userid/handler.py
> +
clean up whitespace

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-face-with-idcard/.dockerignore
> -__pycache__
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-face-with-idcard/.vscode/example-launch.json
> -    "version": "0.2.0",
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-face-with-idcard/models.py
> +    print(event['IdCardName'])
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-face-with-idcard/models.py
> +  # @idcard_image_bytes.setter
dont leave duplicated blocks

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-face-with-idcard/requirements.txt
> -aws_xray_sdk
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-faces/.dockerignore
> -__pycache__
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-faces/handler.py
> +    print(faces)
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/compare-faces/models.py
> +    return self.__bucket
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/detect-faces/.dockerignore
> -__pycache__
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/detect-faces/handler.py
> +def detect_faces_image(image: str) -> dict:
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/index-faces/handler.py
> +        return int(value)
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/index-faces/storage.py
> +    print(face_metadata)
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/liveness-session-result/handler.py
> +client = boto3.client('rekognition')
use REGION environ for consistency with other functions

2023-04-26 16:49 UTC, dr-natetorious commented on src/rekognition/reset/Dockerfile
> -# Define function directory
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/textract/extract-idcard/docparser.py
> +from typing import List, Mapping
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/textract/extract-idcard/handler.py
> -    raise InvalidImageError('ProvisionedThroughputExceeded')
unrelated to changes undo

2023-04-26 16:49 UTC, dr-natetorious commented on src/textract/extract-idcard/requirements.txt
> -aws_xray_sdk
unrelated to changes undo

2023-04-26 18:17 UTC, vineetkachhawaha commented on infra/frontend/cognito/topology.py
> +class RivCognitoForLivenes(Construct):
Just for Liveness

2023-04-26 18:17 UTC, vineetkachhawaha commented on infra/frontend/amplifydeployment/index.py
> +                while (i == False):
change it to jobFlag

2023-04-26 18:18 UTC, vineetkachhawaha commented on README.md
> +REACT_APP_IDENTITYPOOL_ID=REACT_APP_IDENTITYPOOL_ID
Updated with right example

2023-04-26 18:19 UTC, vineetkachhawaha commented on infra/frontend/cognito/topology.py
> +            self, "RIV-Cognito", user_pool_name=riv_stack.stack_name)
Updated to RIV-Cognito-User-Pool

2023-04-26 18:19 UTC, vineetkachhawaha commented on infra/frontend/cognito/topology.py
> +        self.idp = cognito.CfnIdentityPool(self, "RIV-IdentityPool", identity_pool_name=riv_stack.stack_name, allow_unauthenticated_identities=True, cognito_identity_providers=[cognito.CfnIdentityPoo
done

2023-04-27 01:37 UTC, vineetkachhawaha commented on infra/userportal/states/register_idcard.py
> +    # Index the user and complete the operation...
We are extracting ID card details in a separate API calls. Therefore, removing this functionally call  from Register ID Card state

2023-04-27 01:46 UTC, vineetkachhawaha commented on one-click.sh
> -export API_END_POINT=`awscliv2 cloudformation describe-stacks --stack-name $RIV_STACK_NAME --query "Stacks[0].Outputs[0].OutputValue" --output text`
I'm setting the S3_REGIOn in the code at line 130  -> export S3_REGION=${S3_REGION:-$(aws configure get region)}

2023-04-27 01:47 UTC, vineetkachhawaha commented on one-click.sh
> +CDK_REGION=S3_REGION cdk deploy -a ./app.py --require-approval never
Yeah but I'm setting the region from the aws configure region set. - > export S3_REGION=${S3_REGION:-$(aws configure get region)}
I removed the S3 bucker creation code as that bucket was not used in the code and it was always empty

2023-04-27 01:49 UTC, vineetkachhawaha commented on src/frontend/README.md
> +### `npm test`
I was showing as a header those commands.. Updated the code to show as command only.

2023-04-27 01:50 UTC, vineetkachhawaha commented on src/frontend/amplify.yml
> +        - npm i
Yes

2023-04-27 02:05 UTC, vineetkachhawaha commented on src/rekognition/compare-face-with-idcard/models.py
> +    print(event['IdCardName'])
This is changes to support the liveness. After Liveness check we get 1 ref img and audit img with s3 path. Therefore, instead of using the image byte in response I'm passing s3 bucker and key.

2023-04-27 13:51 UTC, vineetkachhawaha commented on README.md
> -c:\git\rekoginition-identity-verification\docker-deploy\debug.bat
added the instructions

2023-04-27 16:18 UTC, closed without merging